apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  type: NodePort
  selector:
    app: cicd-demo
  ports:
    - port: 80          # Service 集群内端口
      targetPort: 8080  # 容器端口
      nodePort: 30080   # 节点端口,配合 kind extraPortMappings 后浏览器访问 localhost:30080
